# Generated by Django 3.0.4 on 2020-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraddres'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddres',
            name='order_id',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
