# Generated by Django 3.0.4 on 2020-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200413_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddres',
            name='order',
            field=models.CharField(max_length=120),
        ),
    ]
