# Generated by Django 3.0.4 on 2020-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200322_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaton',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=120),
        ),
    ]
