# Generated by Django 3.0.4 on 2020-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variaton_category'),
        ('shopping_cart', '0006_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product.Variaton'),
        ),
    ]
