# Generated by Django 3.0.4 on 2020-04-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200324_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_total',
            new_name='tax_total',
        ),
    ]
