# Generated by Django 3.0.4 on 2020-04-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_useraddres_order'),
        ('order', '0013_auto_20200414_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.UserAddres'),
        ),
    ]
